package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"

	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/server/biz"
)

// MyWorkspace is the resolver for the myWorkspace field.
func (r *queryResolver) MyWorkspace(ctx context.Context, projectID *objects.GUID) (*biz.PersonalWorkspace, error) {
	return r.personalService.Workspace(ctx, projectID)
}

// MyDashboard is the resolver for the myDashboard field.
func (r *queryResolver) MyDashboard(ctx context.Context, input biz.PersonalUsageInput) (*biz.PersonalDashboard, error) {
	return r.personalService.Dashboard(ctx, input)
}

// MyModels is the resolver for the myModels field.
func (r *queryResolver) MyModels(ctx context.Context, input *PersonalModelsInput) ([]*biz.PersonalModel, error) {
	scope := biz.PersonalScope{}
	search := ""
	if input != nil {
		scope.ProjectID, scope.APIKeyID = input.ProjectID, input.APIKeyID
		if input.Search != nil {
			search = *input.Search
		}
	}
	return r.personalService.Models(ctx, scope, search)
}
